const int minFilterAttributes = 2;
const languages = {
  "ar": "العربية",
  "cs": "Čeština",
  "da": "Dansk",
  "de": "Deutsch",
  "en": "English",
  "es": "Español",
  "et": "Eesti",
  "fa": "فارسی",
  "fr": "Français",
  "hi": "हिन्दी",
  "he": "עברית",
  "hr": "Hrvatski",
  "id": "Bahasa Indonesia",
  "it": "Italiano",
  "lv": "Latviešu",
  "lt": "Lietuvių",
  "hu": "Magyar",
  "nl": "Nederlands",
  "ja": "日本語",
  "nb": "Norsk",
  "pa": "ਪੰਜਾਬੀ",
  "pl": "Polski",
  "pt": "Português",
  "ro": "Română",
  "ru": "Русский",
  "sk": "Slovenčina",
  "sl": "Slovenščina",
  "sr": "Српски / srpski",
  "sv": "Svenska",
  "fi": "Suomi",
  "uk": "Українська"
};