const int minFilterAttributes = 2;
const languages = {
  "ar_EG": "العربية",
  "bg_BG": "Български",
  "cs_CZ": "Čeština",
  "da_DK": "Dansk",
  "de_DE": "Deutsch",
  "en_US": "English",
  "es_ES": "Español",
  "et_EE": "Eesti",
  "fa_IR": "فارسی",
  "fr_FR": "Français",
  "hi_IN": "हिन्दी",
  "ko_KR": "한국어",
  "hr_HR": "Hrvatski",
  "id_ID": "Bahasa Indonesia",
  "it_IT": "Italiano",
  "he_IL": "עברית",
  "lv_LV": "Latviešu",
  "lt_LT": "Lietuvių",
  "hu_HU": "Magyar",
  "nl_NL": "Nederlands",
  "ja_JP": "日本語",
  "nb_NO": "Norsk",
  "pl_PL": "Polski",
  "pt_PT": "Português",
  "ro_RO": "Română",
  "ru_RU": "Русский",
  "sk_SK": "Slovenčina",
  "sl_SI": "Slovenščina",
  "sr_RS": "Српски",
  "sv_SE": "Svenska",
  "fi_FI": "Suomi",
  "uk_UA": "Українська"
};